In [1]:
import numpy as np

def convert_data(data: dict):
    """
    Convert the given yearly dict into arrays:
    S0: shape (N,)
    K:  shape (N, M)
    sigma: shape (N,)
    """
    years = sorted(data.keys())  # ensure deterministic order

    S0 = np.array([data[y]["S0"] for y in years], dtype=float)
    K  = np.array([data[y]["K_sampled"] for y in years], dtype=float)
    sigma = np.array([data[y]["std"] for y in years], dtype=float)

    return S0, K, sigma

In [2]:
import json
with open("bsm_data_2017_2021_sp500.json", "r") as f:
    data = json.load(f)

S0, K, sigma = convert_data(data)

In [3]:
S0

array([2257.253887, 2695.875134, 2510.564873, 3257.738735, 3699.63053 ])

In [4]:
K

array([[2235., 2245., 2255., 2265., 2275.],
       [2675., 2685., 2695., 2705., 2715.],
       [2490., 2500., 2510., 2520., 2530.],
       [3240., 3250., 3260., 3270., 3280.],
       [3680., 3690., 3700., 3710., 3720.]])

In [5]:
sigma

array([0.06660348, 0.17112474, 0.12504962, 0.34754987, 0.1303283 ])